# Generated by Django 5.0.1 on 2024-01-08 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('prix', models.IntegerField()),
                ('images', models.ImageField(blank=True, null=True, upload_to='media')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
