# Generated by Django 5.0.1 on 2024-01-10 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0002_category_produit_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, to='produits.category'),
        ),
    ]
