# Generated by Django 5.0.1 on 2024-01-10 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0003_alter_produit_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='category',
        ),
        migrations.AddField(
            model_name='produit',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='produits.category'),
        ),
    ]
