# Generated by Django 5.0.1 on 2024-07-15 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(default='default@email.com', max_length=254, unique=True),
        ),
    ]
